Fix/readme example await
node-fetch/node-fetch pull request #1021
Opened 2020-11-29 01:34 UTC by tekwiz

**What is the purpose of this pull request?**

- [x] Documentation update
- [x] Bug fix
- [ ] New feature
- [ ] Other, please explain:

**What changes did you make? (provide an overview)**

Updated examples in the README to:
1. fix an error with file-type fromBuffer -- 4edad8ecea717482b460196f5de9243615ebce1e
2. make examples consistently use async/await -- 9647772869f6de9b21550ec48a1511f054476577
3. show how to use a custom error to store an error response for extraction of the body in the catch statement - e9cc7f1625d92ce211f72baf27ae212bd9e34a45

**Which issue (if any) does this pull request address?**

#1009 

**Is there anything you'd like reviewers to know?**

no

2020-12-01 19:41 UTC, rfoel approved these changes

2020-12-02 08:26 UTC, Richienb requested changes
The examples should assume an environment where top-level await statements are allowed.

2020-12-06 17:04 UTC, tekwiz commented
@Richienb I've converted the example to top-level await.  I also fixed two other minor things in the README while I was at it:  1665988e2493beac877ff9de96ecd35e1c01225c and f4aef932b5fecddae7a078d588d65063acd08c98

2020-12-06 19:14 UTC, Richienb approved these changes

2020-12-06 21:42 UTC, xxczaki approved these changes

2020-12-06 21:42 UTC, merged