Allow falsey signal to act falsey Fix
node-fetch/node-fetch pull request #1050
Opened 2020-12-24 23:37 UTC by tekwiz

**What is the purpose of this pull request?**

- [ ] Documentation update
- [x] Bug fix
- [ ] New feature
- [ ] Other, please explain:

**What changes did you make? (provide an overview)**

This allows a falsey `signal` to be ignored.  e.g. 
```
fetch('https://google.com', { signal: undefined })
```

**Which issue (if any) does this pull request address?**

#1029

**Is there anything you'd like reviewers to know?**

no

2020-12-24 23:42 UTC, tekwiz commented
Note that the decreased coverage is due to existing coverage of <100% and a reduction of the number of times `isAbortSignal` is called in tests. There is no actual reduction in coverage, and there is a new test case specifically for this change.

2020-12-25 22:59 UTC, xxczaki approved these changes

2020-12-25 23:08 UTC, jimmywarting requested changes

2020-12-30 01:46 UTC, Richienb approved these changes

2020-12-30 03:48 UTC, jimmywarting approved these changes

2021-01-01 05:35 UTC, merged