Handle zero-length OK deflate responses (master)
node-fetch/node-fetch pull request #965
Opened 2020-09-25 01:01 UTC by mgoszcz2

**What is the purpose of this pull request?**

- [x] Bug fix

**What changes did you make?**

This fixes an issue where older ISS servers (Definitely 7.5, but I can’t rule out other versions), could respond with a zero-length OK deflate response, hanging node-fetch. This was caused by the body stream never emitting a `data` event. A typical problematic response looks something like this:

```http
HTTP/1.1 200 OK
Content-Encoding: deflate
Content-Length: 0
Server: Microsoft-IIS/7.5
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
```

**Is there anything you'd like reviewers to know?**

This is the master counterpart to the 2.x PR #903, fixes #922 
I had to tweak it a bit compared to the 2.x version because `pump` would incorrectly reject on empty responses.

2020-09-25 01:17 UTC, mgoszcz2 commented
Not really sure how to fix the coverage here. In the original PR adding `pump` (#670), @xxczaki [mentions](https://github.com/node-fetch/node-fetch/pull/670#issuecomment-529225954) that the stream error conditions are hard to test.

2020-10-02 05:30 UTC, uday79936 commented
HTTP/1.1 200 OK
Content-Encoding: deflate
Content-Length: 0
Server: Microsoft-IIS/7.5
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET is change first and merge is accept

2020-10-02 14:02 UTC, mgoszcz2 commented
Don't see what you're saying here, looks like it might be Hacktoberfest spam?

2020-10-21 11:58 UTC, mgoszcz2 commented
Ping @jimmywarting as it’s been a couple weeks. This addresses your comment https://github.com/node-fetch/node-fetch/pull/903#issuecomment-690946225

2020-10-24 03:29 UTC, bitinn requested changes
Sorry for the wait, this PR looks fine to me, but I think a few things can be improved.
 
- If the change on `pump()` error handling is necessary for your tests to pass, then we should probably change all of the instances.

- I would like to see a comment with link to explain special handling of deflate response, so we have a source of the issues

2020-10-24 03:29 UTC, bitinn commented on src/index.js
> +			let body = pump(response_, new PassThrough(), err => {
Sorry for the wait, this PR looks fine to me, but I think a few things can be improved:
 
- If the change on `pump()` error handling is necessary for your tests to pass, then we should probably change all of the instances.

2020-10-24 03:29 UTC, bitinn commented on src/index.js
> +					if (!response) {
- I would like to see a comment with link to explain special handling of deflate response, so we have a source for the code, see my comment above that explains the line `if ((chunk[0] & 0x0F) === 0x08)`

2021-05-05 11:52 UTC, xxczaki commented
@mgoszcz2 Is it ready for review now?

2021-05-06 02:46 UTC, mgoszcz2 commented
I think so @xxczaki. No bother at all, you can see I was in no rush either.

2021-06-26 21:34 UTC, mgoszcz2 commented
Hi, any chance of this getting merged? @xxczaki @bitinn

2022-01-15 22:43 UTC, tekwiz commented
@mgoszcz2 This just needs to be rebased on main.  I can approve once that's done, and I believe @bitinn just needs to re-review after that and we can merge.

2022-01-16 13:01 UTC, mgoszcz2 commented
@tekwiz Thanks. I hope this also means #903 will be merged? Because there was a lot of churn involved in getting to this stage without any merges happening and I don't feel like sinking more time into this pull request. I made #903 to fix a specific issues that was affecting production at a company I no longer work. Unless nothing more is required of me other than a rebase, I'm not willing to continue working on this PR.

2022-01-16 13:47 UTC, bitinn commented
I believe this is addressing the same issue as

https://github.com/node-fetch/node-fetch/issues/1442

I hope Jeff can help to look into it. We are now 2 years away from my initial review, I am happy to merge but we need to make sure it doesn’t introduce any problems to current codebase.

Sent from my iPhone

> On Jan 16, 2022, at 21:01, Maciej Goszczycki ***@***.***> wrote:
> 
> ﻿
> @tekwiz Thanks. I hope this also means #903 will be merged? Because there was a lot of churn involved in getting to this stage without any merges happening and I don't feel like sinking more time into this pull request. I made #903 to fix a specific issues that was affecting production at a company I no longer work. Unless nothing more is required of me other than a rebase, I'm not willing to continue working on this PR.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you were mentioned.

2022-01-16 14:58 UTC, bitinn approved these changes

2022-01-16 15:04 UTC, mgoszcz2 commented
Can you explain what's preventing from #903 from being merged? It's a completely different branch and major version. I wasn't even using 3.x, I only made this PR because I was asked to by Jimmy.

2022-01-16 15:24 UTC, mgoszcz2 commented
I rebased it

2022-01-16 15:30 UTC, mgoszcz2 commented
Regarding, #1442: Yes it's the same issue, and in fact that it's a duplicate of #922 I opened in 2020. In case it's not clear, this PR would've fixed it on the main branch, and #903 would've fixed it on the 2.x branch (but nether has been merged).

2022-01-16 15:34 UTC, bitinn commented
Thx, for 2.x branch backport we can reopen your PR, please ping Jimmy in the comment. I think a lack of active reviewers at the time was preventing it from moving forward.

Sent from my iPhone

> On Jan 16, 2022, at 23:24, Maciej Goszczycki ***@***.***> wrote:
> 
> ﻿
> I rebased it
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you were mentioned.

2022-01-16 18:46 UTC, jimmywarting approved these changes

2022-01-16 21:08 UTC, jimmywarting commented on src/index.js
> +					if (err) {
nit pick, can you quickly change all `err` to `error` to make the linter happy?

must say that i'm not a huge fan of xo... like standardjs more...

2022-01-16 21:57 UTC, JefferyHus approved these changes
Looks good to me. With only changing `err` to `error`

2022-01-16 22:25 UTC, mgoszcz2 commented
Done. Please also consider merging/re-opening #903 when you have some time.

2022-01-16 22:56 UTC, jimmywarting commented
@mgoszcz2

> Done. Please also consider merging/re-opening #903 when you have some time.

haven't looked trough (reviewed) it yet... it's closed... what dose that pr do that this pr dose not solve?

2022-01-16 23:28 UTC, mgoszcz2 commented
It fixes this bug for the 2.x branch. You closed it. I do not understand why. When I asked if it will be merged and you said it will be. That was September 2020. I only made this PR because you asked for it to be ported to the main branch too. Please look over your own messages in #903. In retrospect I should have never offered to fix the main branch if I knew merging 6 lines of code in two branches would take nearly two years.

2022-01-16 23:37 UTC, mgoszcz2 commented
I pinged you at the request of David. Please read the messages above.

> Thx, for 2.x branch backport we can reopen your PR, please ping Jimmy in the comment. I think a lack of active reviewers at the time was preventing it from moving forward.

2022-01-16 23:41 UTC, merged

2022-01-16 23:42 UTC, jimmywarting commented
merged, thx for the fix, again sry that it took so long